from http import HTTPStatus

from fastapi import APIRouter, HTTPException

from api.app import schemas
from api.app.constants import API_PREFIX
from src.framework.repository.quality_run_repository import (
    QualityRunRepository,
)


router = APIRouter(
    prefix=f"{API_PREFIX}/quality",
    tags=["Quality"],
)


repository = QualityRunRepository()


@router.get(
    "/latest",
    status_code=HTTPStatus.OK,
    response_model=schemas.QualityMetricsResponse,
    summary="Get latest data quality metrics",
    description=(
        "Returns the latest data quality metrics "
        "generated by the ETL pipeline."
    ),
    operation_id="get_latest_quality_metrics",
)
def get_latest_quality_metrics():

    metrics = repository.get_latest()

    if metrics is None:

        raise HTTPException(
            status_code=HTTPStatus.NOT_FOUND,
            detail="No quality metrics available.",
        )

    return metrics